import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        regular: ['Inter', 'system-ui', 'sans-serif'],
        italic: ['Inter', 'system-ui', 'sans-serif'],
        medium: ['Inter', 'system-ui', 'sans-serif'],
        semibold: ['Inter', 'system-ui', 'sans-serif'],
        bold: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xxs': ['0.625rem', { lineHeight: '1.0' }],
        'xs': ['0.75rem', { lineHeight: '1.3' }],
        'base': ['0.875rem', { lineHeight: '1.45' }],
        'base-fit': ['0.875rem', { lineHeight: '1.2' }],
        'md': ['1rem', { lineHeight: '1.5' }],
        'heading-xs': ['1.5rem', { lineHeight: '1.2' }],
        'heading-md': ['2rem', { lineHeight: '1.1' }],
        'heading-2xl': ['3rem', { lineHeight: '1.1' }],
        'display-xl': ['4.5rem', { lineHeight: '1.0' }],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem', 
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '2rem',
        '8': '2.5rem',
        '9': '3rem',
        '10': '3.5rem',
        '11': '4rem',
        '12': '4.5rem',
        '13': '5rem',
        '14': '5.5rem',
        '15': '6rem',
      },
      colors: {
        border: "oklch(var(--border))",
        input: "oklch(var(--input))",
        ring: "oklch(var(--ring))",
        background: "oklch(var(--background))",
        foreground: "oklch(var(--foreground))",
        primary: {
          DEFAULT: "oklch(var(--primary))",
          foreground: "oklch(var(--primary-foreground))",
          50: "oklch(var(--primary-50))",
          100: "oklch(var(--primary-100))",
          200: "oklch(var(--primary-200))",
          300: "oklch(var(--primary-300))",
          400: "oklch(var(--primary-400))",
          500: "oklch(var(--primary-500))",
          600: "oklch(var(--primary-600))",
          700: "oklch(var(--primary-700))",
          800: "oklch(var(--primary-800))",
          900: "oklch(var(--primary-900))",
        },
        secondary: {
          DEFAULT: "oklch(var(--secondary))",
          foreground: "oklch(var(--secondary-foreground))",
          50: "oklch(var(--secondary-50))",
          100: "oklch(var(--secondary-100))",
          200: "oklch(var(--secondary-200))",
          300: "oklch(var(--secondary-300))",
          400: "oklch(var(--secondary-400))",
          500: "oklch(var(--secondary-500))",
          600: "oklch(var(--secondary-600))",
          700: "oklch(var(--secondary-700))",
          800: "oklch(var(--secondary-800))",
          900: "oklch(var(--secondary-900))",
        },
        gray: {
          50: "oklch(var(--gray-50))",
          100: "oklch(var(--gray-100))",
          200: "oklch(var(--gray-200))",
          300: "oklch(var(--gray-300))",
          400: "oklch(var(--gray-400))",
          500: "oklch(var(--gray-500))",
          600: "oklch(var(--gray-600))",
          700: "oklch(var(--gray-700))",
          800: "oklch(var(--gray-800))",
          900: "oklch(var(--gray-900))",
        },
        error: {
          50: "oklch(var(--error-50))",
          100: "oklch(var(--error-100))",
          200: "oklch(var(--error-200))",
          300: "oklch(var(--error-300))",
          400: "oklch(var(--error-400))",
          500: "oklch(var(--error-500))",
          600: "oklch(var(--error-600))",
          700: "oklch(var(--error-700))",
          800: "oklch(var(--error-800))",
          900: "oklch(var(--error-900))",
        },
        success: {
          50: "oklch(var(--success-50))",
          100: "oklch(var(--success-100))",
          200: "oklch(var(--success-200))",
          300: "oklch(var(--success-300))",
          400: "oklch(var(--success-400))",
          500: "oklch(var(--success-500))",
          600: "oklch(var(--success-600))",
          700: "oklch(var(--success-700))",
          800: "oklch(var(--success-800))",
          900: "oklch(var(--success-900))",
        },
        warning: {
          50: "oklch(var(--warning-50))",
          100: "oklch(var(--warning-100))",
          200: "oklch(var(--warning-200))",
          300: "oklch(var(--warning-300))",
          400: "oklch(var(--warning-400))",
          500: "oklch(var(--warning-500))",
          600: "oklch(var(--warning-600))",
          700: "oklch(var(--warning-700))",
          800: "oklch(var(--warning-800))",
          900: "oklch(var(--warning-900))",
        },
        destructive: {
          DEFAULT: "oklch(var(--destructive))",
          foreground: "oklch(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "oklch(var(--muted))",
          foreground: "oklch(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "oklch(var(--accent))",
          foreground: "oklch(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "oklch(var(--popover))",
          foreground: "oklch(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "oklch(var(--card))",
          foreground: "oklch(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "oklch(var(--sidebar-background))",
          foreground: "oklch(var(--sidebar-foreground))",
          primary: "oklch(var(--sidebar-primary))",
          "primary-foreground": "oklch(var(--sidebar-primary-foreground))",
          accent: "oklch(var(--sidebar-accent))",
          "accent-foreground": "oklch(var(--sidebar-accent-foreground))",
          border: "oklch(var(--sidebar-border))",
          ring: "oklch(var(--sidebar-ring))",
        },
        iridium: "oklch(var(--iridium))",
        "frost-blue": "oklch(var(--frost-blue))",
      },
      boxShadow: {
        'xxs': '0 1px 2px oklch(0.266 0.055 261.6 / 0.12)',
        'xs': '0 4px 16px -2px oklch(0.266 0.055 261.6 / 0.06)',
        'sm': '0 4px 32px -2px oklch(0.266 0.055 261.6 / 0.06)',
        'md': '0 16px 48px -4px oklch(0.266 0.055 261.6 / 0.06)',
        'xl': '0 32px 80px -4px oklch(0.266 0.055 261.6 / 0.12)',
        'xxl': '0 64px 80px -4px oklch(0.266 0.055 261.6 / 0.12)',
        'primary-2px': '0px 0px 2px 2px oklch(0.835 0.155 264.2 / 1)',
        'primary-4px': '0px 0px 0px 4px oklch(0.919 0.090 262.6 / 1)',
        'secondary-2px': '0px 0px 2px 2px oklch(0.893 0.038 253.6 / 1)',
        'secondary-4px': '0px 0px 0px 4px oklch(0.893 0.038 253.6 / 1)',
        'error-2px': '0px 0px 2px 2px oklch(0.816 0.096 109.4 / 1)',
        'error-4px': '0px 0px 0px 4px oklch(0.908 0.037 123.7 / 1)',
        'success-2px': '0px 0px 2px 2px oklch(0.835 0.035 302.7 / 1)',
        'success-4px': '0px 0px 0px 4px oklch(0.835 0.035 302.7 / 1)',
        'warning-2px': '0px 0px 2px 2px oklch(0.884 0.138 91.6 / 1)',
        'warning-4px': '0px 0px 0px 4px oklch(0.884 0.138 91.6 / 1)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
