import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "rgb(var(--border))",
        input: "rgb(var(--input))",
        ring: "rgb(var(--ring))",
        background: "rgb(var(--background))",
        foreground: "rgb(var(--foreground))",
        primary: {
          50: "rgb(var(--primary-50))",
          100: "rgb(var(--primary-100))",
          200: "rgb(var(--primary-200))",
          300: "rgb(var(--primary-300))",
          400: "rgb(var(--primary-400))",
          500: "rgb(var(--primary-500))",
          600: "rgb(var(--primary-600))",
          700: "rgb(var(--primary-700))",
          800: "rgb(var(--primary-800))",
          900: "rgb(var(--primary-900))",
          DEFAULT: "rgb(var(--primary))",
          foreground: "rgb(var(--primary-foreground))",
        },
        secondary: {
          50: "rgb(var(--secondary-50))",
          100: "rgb(var(--secondary-100))",
          200: "rgb(var(--secondary-200))",
          300: "rgb(var(--secondary-300))",
          400: "rgb(var(--secondary-400))",
          500: "rgb(var(--secondary-500))",
          600: "rgb(var(--secondary-600))",
          700: "rgb(var(--secondary-700))",
          800: "rgb(var(--secondary-800))",
          900: "rgb(var(--secondary-900))",
          DEFAULT: "rgb(var(--secondary))",
          foreground: "rgb(var(--secondary-foreground))",
        },
        gray: {
          50: "rgb(var(--gray-50))",
          100: "rgb(var(--gray-100))",
          200: "rgb(var(--gray-200))",
          300: "rgb(var(--gray-300))",
          400: "rgb(var(--gray-400))",
          500: "rgb(var(--gray-500))",
          600: "rgb(var(--gray-600))",
          700: "rgb(var(--gray-700))",
          800: "rgb(var(--gray-800))",
          900: "rgb(var(--gray-900))",
        },
        error: {
          50: "rgb(var(--error-50))",
          100: "rgb(var(--error-100))",
          200: "rgb(var(--error-200))",
          300: "rgb(var(--error-300))",
          400: "rgb(var(--error-400))",
          500: "rgb(var(--error-500))",
          600: "rgb(var(--error-600))",
          700: "rgb(var(--error-700))",
          800: "rgb(var(--error-800))",
          900: "rgb(var(--error-900))",
          DEFAULT: "rgb(var(--error-500))",
        },
        success: {
          50: "rgb(var(--success-50))",
          100: "rgb(var(--success-100))",
          200: "rgb(var(--success-200))",
          300: "rgb(var(--success-300))",
          400: "rgb(var(--success-400))",
          500: "rgb(var(--success-500))",
          600: "rgb(var(--success-600))",
          700: "rgb(var(--success-700))",
          800: "rgb(var(--success-800))",
          900: "rgb(var(--success-900))",
          DEFAULT: "rgb(var(--success-500))",
        },
        warning: {
          50: "rgb(var(--warning-50))",
          100: "rgb(var(--warning-100))",
          200: "rgb(var(--warning-200))",
          300: "rgb(var(--warning-300))",
          400: "rgb(var(--warning-400))",
          500: "rgb(var(--warning-500))",
          600: "rgb(var(--warning-600))",
          700: "rgb(var(--warning-700))",
          800: "rgb(var(--warning-800))",
          900: "rgb(var(--warning-900))",
          DEFAULT: "rgb(var(--warning-500))",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive))",
          foreground: "rgb(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "rgb(var(--muted))",
          foreground: "rgb(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "rgb(var(--accent))",
          foreground: "rgb(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "rgb(var(--popover))",
          foreground: "rgb(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "rgb(var(--card))",
          foreground: "rgb(var(--card-foreground))",
        },
        iridium: "rgb(var(--iridium))",
        "frost-blue": "rgb(var(--frost-blue))",
      },
      fontFamily: {
        regular: "var(--font-regular)",
        italic: "var(--font-italic)",
        medium: "var(--font-medium)",
        semibold: "var(--font-semibold)",
        bold: "var(--font-bold)",
        sans: "var(--font-regular)",
      },
      fontSize: {
        xxs: ["0.625rem", { lineHeight: "100%" }],
        xs: ["0.75rem", { lineHeight: "130%" }],
        sm: ["0.875rem", { lineHeight: "140%" }],
        base: ["0.875rem", { lineHeight: "145%" }],
        "base-fit": ["0.875rem", { lineHeight: "100%" }],
        md: ["1rem", { lineHeight: "150%" }],
        "md-fit": ["1rem", { lineHeight: "100%" }],
        lg: ["1.125rem", { lineHeight: "160%" }],
        xl: ["1.25rem", { lineHeight: "170%" }],
        "2xl": ["1.5rem", { lineHeight: "180%" }],
        "3xl": ["1.875rem", { lineHeight: "190%" }],
        "4xl": ["2.25rem", { lineHeight: "200%" }],
        "5xl": ["3rem", { lineHeight: "210%" }],
        "6xl": ["3.75rem", { lineHeight: "220%" }],
        "heading-xs": ["1.5rem", { lineHeight: "120%" }],
        "heading-sm": ["1.75rem", { lineHeight: "125%" }],
        "heading-md": ["2rem", { lineHeight: "130%" }],
        "heading-lg": ["2.5rem", { lineHeight: "135%" }],
        "heading-xl": ["3rem", { lineHeight: "140%" }],
        "heading-2xl": ["3rem", { lineHeight: "120%" }],
        "display-sm": ["2.5rem", { lineHeight: "120%" }],
        "display-md": ["3.5rem", { lineHeight: "110%" }],
        "display-lg": ["4rem", { lineHeight: "105%" }],
        "display-xl": ["4.5rem", { lineHeight: "100%" }],
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        11: "var(--space-11)",
        12: "var(--space-12)",
        13: "var(--space-13)",
        14: "var(--space-14)",
        15: "var(--space-15)",
      },
      boxShadow: {
        xxs: "var(--shadow-xxs)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        xl: "var(--shadow-xl)",
        xxl: "var(--shadow-xxl)",
        "primary-2px": "var(--shadow-primary-2px)",
        "primary-4px": "var(--shadow-primary-4px)",
        "secondary-2px": "var(--shadow-secondary-2px)",
        "secondary-4px": "var(--shadow-secondary-4px)",
        "error-2px": "var(--shadow-error-2px)",
        "error-4px": "var(--shadow-error-4px)",
        "success-2px": "var(--shadow-success-2px)",
        "success-4px": "var(--shadow-success-4px)",
        "warning-2px": "var(--shadow-warning-2px)",
        "warning-4px": "var(--shadow-warning-4px)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      transitionProperty: {
        smooth: "var(--transition-smooth)",
        bounce: "var(--transition-bounce)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
            opacity: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
            opacity: "1",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
            opacity: "1",
          },
          to: {
            height: "0",
            opacity: "0",
          },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeOutUp: {
          from: { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(-20px)" },
        },
        moveUp: {
          from: { transform: "translateY(10px)" },
          to: { transform: "translateY(0)" },
        },
        moveDown: {
          from: { transform: "translateY(-10px)" },
          to: { transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 5px oklch(0.548 0.140 255.9 / 0.5)" },
          "50%": { boxShadow: "0 0 20px oklch(0.548 0.140 255.9 / 0.8)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.3s ease-out",
        "accordion-up": "accordion-up 0.3s ease-out",
        fadeIn: "fadeIn 0.3s ease-out",
        scaleIn: "scaleIn 0.2s ease-out",
        slideUp: "slideUp 0.3s ease-out",
        fadeInDown: "fadeInDown 0.3s ease-out",
        fadeOutUp: "fadeOutUp 0.3s ease-out",
        moveUp: "moveUp 0.3s ease-out",
        moveDown: "moveDown 0.3s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
